/**
 * Created by nathanjones on 09/06/15.
 */


angular.module('nsTrial.services', [])
  .service('nsImagesService', function ($q) {

    var CONSTANTS = {
      REF: "ImageRef",
      LAT: "SubjectLatitude",
      LNG: "SubjectLongitude",
      DESC: "Description1"
    };
    this.CONSTANTS = CONSTANTS;

    // data.n-somerset.gov.uk/Download/culture-leisure-and-heritage/images
    var data = [
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "1",
        "ImageName": "Weston-super-Mare",
        "Summary": "Vista showing Marine Lake, Weston-super-Mare",
        "Description1": "View of Marine Lake, Weston-super-Mare",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Marine Lake\",\"Postcard\"]",
        "Address1": "Marine Lake",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16446440230/",
        "Copyright": "Copyright under review",
        "Subject": "Marine Lake",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24130053",
        "SubjectEasting": "331163",
        "SubjectNorthing": "161985",
        "SubjectLatitude": "51.3527436",
        "SubjectLongitude": "-2.9898917",
        "OriginEasting": "331000",
        "OriginNorthing": "162095",
        "OriginLatitude": "51.3527436",
        "OriginLongitude": "-2.9898917",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331163&y=161985",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�21'09.9\"N+2�59'23.6\"W/@51.3527436,-2.9898917,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "2",
        "ImageName": "Weston-super-Mare",
        "Summary": "Vista showing Marine Lake, Weston-super-Mare",
        "Description1": "View of Marine Lake, Weston-super-Mare",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Marine Lake\",\"Postcard\"]",
        "Address1": "Marine Lake",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16426149567/",
        "Copyright": "Copyright under review",
        "Subject": "Marine Lake",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24130053",
        "SubjectEasting": "331163",
        "SubjectNorthing": "161985",
        "SubjectLatitude": "51.3527436",
        "SubjectLongitude": "-2.9898917",
        "OriginEasting": "331000",
        "OriginNorthing": "162095",
        "OriginLatitude": "51.3527436",
        "OriginLongitude": "-2.9898917",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331163&y=161985",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�21'09.9\"N+2�59'23.6\"W/@51.3527436,-2.9898917,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "3",
        "ImageName": "Weston-super-Mare",
        "Summary": "Vista showing Marine Lake, Weston-super-Mare",
        "Description1": "View of Marine Lake, Weston-super-Mare",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Marine Lake\",\"Postcard\"]",
        "Address1": "Marine Lake",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16632790602/",
        "Copyright": "Copyright under review",
        "Subject": "Marine Lake",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24130053",
        "SubjectEasting": "331163",
        "SubjectNorthing": "161985",
        "SubjectLatitude": "51.3527436",
        "SubjectLongitude": "-2.9898917",
        "OriginEasting": "331000",
        "OriginNorthing": "162095",
        "OriginLatitude": "51.3527436",
        "OriginLongitude": "-2.9898917",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331163&y=161985",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�21'09.9\"N+2�59'23.6\"W/@51.3527436,-2.9898917,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "4",
        "ImageName": "Weston-super-Mare",
        "Summary": "Vista showing Marine Lake, Weston-super-Mare",
        "Description1": "View of Marine Lake, Weston-super-Mare",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Marine Lake\",\"Postcard\"]",
        "Address1": "Marine Lake",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16426149727/",
        "Copyright": "Copyright under review",
        "Subject": "Marine Lake",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24130053",
        "SubjectEasting": "331163",
        "SubjectNorthing": "161985",
        "SubjectLatitude": "51.3527436",
        "SubjectLongitude": "-2.9898917",
        "OriginEasting": "331000",
        "OriginNorthing": "162095",
        "OriginLatitude": "51.3527436",
        "OriginLongitude": "-2.9898917",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331163&y=161985",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�21'09.9\"N+2�59'23.6\"W/@51.3527436,-2.9898917,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "5",
        "ImageName": "Weston-super-Mare",
        "Summary": "Interior view of Winter Gardens, Weston-super-Mare showing a music concert",
        "Description1": "Interior view of Winter Gardens, Weston-super-Mare showing a music concert",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16446083198/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "6",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of Winter Gardens, Weston-super-Mare showing the site and gardens",
        "Description1": "Exterior view of Winter Gardens, Weston-super-Mare showing the site and gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16633246715/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "7",
        "ImageName": "Weston-super-Mare",
        "Summary": "Interior view of Winter Gardens, Weston-super-Mare showing ballroom dancing",
        "Description1": "Interior view of Winter Gardens, Weston-super-Mare showing ballroom dancing",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16425953517/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "8",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of Winter Gardens, Weston-super-Mare showing the front of the site facing Beach Road",
        "Description1": "Exterior view of Winter Gardens, Weston-super-Mare showing the front of the site facing Beach Road",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16425953697/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "9",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of Winter Gardens, Weston-super-Mare showing the pavillion and gardens",
        "Description1": "Exterior view of Winter Gardens, Weston-super-Mare showing the pavillion and gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16425953707/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "10",
        "ImageName": "Weston-super-Mare",
        "Summary": "Interior view of Winter Gardens, Weston-super-Mare showing singer and pianist",
        "Description1": "Interior view of Winter Gardens, Weston-super-Mare showing singer and pianist",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16633246755/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "11",
        "ImageName": "Weston-super-Mare",
        "Summary": "Interior view of Winter Gardens, Weston-super-Mare ballroom",
        "Description1": "Interior view of Winter Gardens, Weston-super-Mare ballroom",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16446245630/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "12",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of Winter Gardens, Weston-super-Mare showing a mayoral parade",
        "Description1": "Exterior view of Winter Gardens, Weston-super-Mare showing a mayoral parade",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16632595472/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "13",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of Winter Gardens, Weston-super-Mare showing a parade",
        "Description1": "Exterior view of Winter Gardens, Weston-super-Mare showing a parade",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16447453839/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "14",
        "ImageName": "Weston-super-Mare",
        "Summary": "Interior view of Winter Gardens, Weston-super-Mare showing a choir in the ballroom",
        "Description1": "Interior view of Winter Gardens, Weston-super-Mare showing a choir in the ballroom",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16011087024/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "15",
        "ImageName": "Weston-super-Mare",
        "Summary": "Interior view of the Winter Gardens, Weston-super-Mare showing an orchestra in the ballroom",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16013487243/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "16",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of the Winter Gardens, Weston-super-Mare showing the exterior and gardens",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16447453849/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "17",
        "ImageName": "Weston-super-Mare",
        "Summary": "Interior view of the Winter Gardens, Weston-super-Mare showing an event in Ballroom",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16446083478/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "18",
        "ImageName": "Weston-super-Mare",
        "Summary": "Interior view of the Winter Gardens, Weston-super-Mare showing boxing",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16446245820/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "19",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of the Winter Gardens, Weston-super-Mare showing tennis courts",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16633246935/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "20",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of the Winter Gardens, Weston-super-Mare showing gardens in full bloom",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16446245890/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "21",
        "ImageName": "Weston-super-Mare",
        "Summary": "Interior view of the Winter Gardens, Weston-super-Mare showing the pergola and water garden",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16632595682/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "22",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of the Winter Gardens, Weston-super-Mare from Beach Road",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16632169141/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "23",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of the Winter Gardens, Weston-super-Mare showing the exterior at night",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16013487413/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "24",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of the Winter Gardens, Weston-super-Mare showing  the spectacular gardens",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16632595792/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "25",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of the Winter Gardens, Weston-super-Mare showing the domed roof",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16013487443/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "26",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of the Winter Gardens, Weston-super-Mare showing the front view from Royal Parade",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16425954137/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "27",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of the Winter Gardens, Weston-super-Mare showing roof shot facing pier",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16011087254/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "28",
        "ImageName": "Weston-super-Mare",
        "Summary": "Exterior view of the Winter Gardens, Weston-super-Mare showing a view from beach",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16447454089/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "29",
        "ImageName": "Weston-super-Mare",
        "Summary": "A view of the Winter Gardens, Weston-super-Mare showing the exterior at night",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16632595882/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "30",
        "ImageName": "Weston-super-Mare",
        "Summary": "Postcard of the Winter Gardens, Weston-super-Mare showing the exterior and gardens",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16607286966/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "31",
        "ImageName": "Weston-super-Mare",
        "Summary": "A view of the Winter Gardens, Weston-super-Mare showing the front view from Royal Parade",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16446083728/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "32",
        "ImageName": "Weston-super-Mare",
        "Summary": "A view of the Winter Gardens, Weston-super-Mare showing the exterior and gardens",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16013487573/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "33",
        "ImageName": "Weston-super-Mare",
        "Summary": "The Winter Gardens, Weston-super-Mare showing the water gardens",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16011087424/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "34",
        "ImageName": "Weston-super-Mare",
        "Summary": "The Ballroom, Winter Gardens, Weston-super-Mare",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16632169311/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "35",
        "ImageName": "Weston-super-Mare",
        "Summary": "The Ballroom, Winter Gardens, Weston-super-Mare",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16011087474/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "36",
        "ImageName": "Weston-super-Mare",
        "Summary": "Interior view of the Winter Gardens, Weston-super-Mare showing a seaonsal flower show",
        "Description1": "Winter Gardens",
        "Type": "Postcard",
        "Tags": "[\"Weston-super-Mare\", \"Winter Gardens\",\"Postcard\"]",
        "Address1": "Winter Gardens",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1AJ",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16446246200/",
        "Copyright": "Copyright under review",
        "Subject": "Winter Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "UPRN": "24001749",
        "SubjectEasting": "331739",
        "SubjectNorthing": "161615",
        "SubjectLatitude": "51.3494868",
        "SubjectLongitude": "-2.9815505",
        "OriginEasting": "331700",
        "OriginNorthing": "161600",
        "OriginLatitude": "51.3494868",
        "OriginLongitude": "-2.9815505",
        "NSCMapLink": "http://map.n-somerset.gov.uk/MyNS.html?scale=2000&x=331739&y=161615",
        "GoogleMapLink": "https://www.google.co.uk/maps/place/51�20'58.1\"N+2�58'53.6\"W/@51.3494868,-2.9815505,17z"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "37",
        "ImageName": "Weston-super-Mare",
        "Summary": "Anchor Head",
        "Description1": "Anchor Head",
        "Type": "Postcard",
        "Address1": "Anchor Head",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16642813655/",
        "Copyright": "Copyright under review",
        "Subject": "Anchor Head",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "38",
        "ImageName": "Weston-super-Mare",
        "Summary": "Atlantic House Beach Road",
        "Description1": "Atlantic House Beach Road",
        "Type": "Postcard",
        "Address1": "Atlantic House",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16457119200/",
        "Copyright": "Copyright under review",
        "Subject": "Atlantic House Beach Road",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "39",
        "ImageName": "Weston-super-Mare",
        "Summary": "Beach Road",
        "Description1": "Beach Road",
        "Type": "Postcard",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16644512775/",
        "Copyright": "Copyright under review",
        "Subject": "Beach Road",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "40",
        "ImageName": "Weston-super-Mare",
        "Summary": "Boulevard",
        "Description1": "Boulevard",
        "Type": "Postcard",
        "Address2": "Boulevard",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16437651747/",
        "Copyright": "Copyright under review",
        "Subject": "Boulevard",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "41",
        "ImageName": "Weston-super-Mare",
        "Summary": "Boulevard",
        "Description1": "Boulevard",
        "Type": "Postcard",
        "Address2": "Boulevard",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16437651777/",
        "Copyright": "Copyright under review",
        "Subject": "Boulevard",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "42",
        "ImageName": "Weston-super-Mare",
        "Summary": "Donkeys",
        "Description1": "Boulevard",
        "Type": "Postcard",
        "Address2": "Boulevard",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16437651807/",
        "Copyright": "Copyright under review",
        "Subject": "Boulevard",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "43",
        "ImageName": "Weston-super-Mare",
        "Summary": "Donkeys",
        "Description1": "Donkeys",
        "Type": "Postcard",
        "Address1": "Beach",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16643983922/",
        "Copyright": "Copyright under review",
        "Subject": "Donkeys",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "44",
        "ImageName": "Weston-super-Mare",
        "Summary": "Donkeys",
        "Description1": "Donkeys",
        "Type": "Postcard",
        "Address1": "Beach",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16643983972/",
        "Copyright": "Copyright under review",
        "Subject": "Donkeys",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "45",
        "ImageName": "Weston-super-Mare",
        "Summary": "Donkeys",
        "Description1": "Donkeys",
        "Type": "Postcard",
        "Address1": "Beach",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16457595160/",
        "Copyright": "Copyright under review",
        "Subject": "Donkeys",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "46",
        "ImageName": "Weston-super-Mare",
        "Summary": "Donkeys",
        "Description1": "Donkeys",
        "Type": "Postcard",
        "Address1": "Beach",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16458811739/",
        "Copyright": "Copyright under review",
        "Subject": "Donkeys",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "47",
        "ImageName": "Weston-super-Mare",
        "Summary": "Donkeys",
        "Description1": "Donkeys",
        "Type": "Postcard",
        "Address1": "Beach",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16025087723/",
        "Copyright": "Copyright under review",
        "Subject": "Donkeys",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "48",
        "ImageName": "Weston-super-Mare",
        "Summary": "Italian Gardens",
        "Description1": "Donkeys",
        "Type": "Postcard",
        "Address1": "Beach",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16437689427/",
        "Copyright": "Copyright under review",
        "Subject": "Vista",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "49",
        "ImageName": "Weston-super-Mare",
        "Summary": "High Street",
        "Description1": "Italian Gardens",
        "Type": "Postcard",
        "Address1": "Italian Gardens",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16025161663/",
        "Copyright": "Copyright under review",
        "Subject": "Italian Gardens",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "50",
        "ImageName": "Weston-super-Mare",
        "Summary": "Lower Church Road",
        "Description1": "High Street",
        "Type": "Postcard",
        "Address2": "High Street",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16025161693/",
        "Copyright": "Copyright under review",
        "Subject": "High Street",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "51",
        "ImageName": "Weston-super-Mare",
        "Summary": "Oxford Street",
        "Description1": "Lower Church Road",
        "Type": "Postcard",
        "Address2": "Lower Church Road",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16022794164/",
        "Copyright": "Copyright under review",
        "Subject": "Lower Church Road",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "52",
        "ImageName": "Weston-super-Mare",
        "Summary": "Playhouse Theatre interior",
        "Description1": "Oxford Street",
        "Type": "Postcard",
        "Address2": "Oxford Street",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16025208513/",
        "Copyright": "Copyright under review",
        "Subject": "Oxford Street",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "53",
        "ImageName": "Weston-super-Mare",
        "Summary": "Playhouse Theatre interior",
        "Description1": "Playhouse Theatre interior",
        "Type": "Postcard",
        "Address1": "Playhouse Theatre",
        "Address2": "High Street",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1HP",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16457731000/",
        "Copyright": "Copyright under review",
        "Subject": "Playhouse Theatre interior",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "54",
        "ImageName": "Weston-super-Mare",
        "Summary": "Regent Street",
        "Description1": "Playhouse Theatre interior",
        "Type": "Postcard",
        "Address1": "Playhouse Theatre",
        "Address2": "High Street",
        "Address3": "Weston-super-Mare",
        "Postcode": "BS23 1HP",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16619198006/",
        "Copyright": "Copyright under review",
        "Subject": "Playhouse Theatre interior",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "55",
        "ImageName": "Weston-super-Mare",
        "Summary": "Regent Street",
        "Description1": "Regent Street",
        "Type": "Postcard",
        "Address2": "Regent Street",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16457583538/",
        "Copyright": "Copyright under review",
        "Subject": "Regent Street",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "56",
        "ImageName": "Weston-super-Mare",
        "Summary": "Regent Street",
        "Description1": "Regent Street",
        "Type": "Postcard",
        "Address2": "Regent Street",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16025258743/",
        "Copyright": "Copyright under review",
        "Subject": "Regent Street",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "57",
        "ImageName": "Weston-super-Mare",
        "Summary": "Regent Street",
        "Description1": "Regent Street",
        "Type": "Postcard",
        "Address2": "Regent Street",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16458980469/",
        "Copyright": "Copyright under review",
        "Subject": "Regent Street",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "58",
        "ImageName": "Weston-super-Mare",
        "Summary": "Regent Street",
        "Description1": "Regent Street",
        "Type": "Postcard",
        "Address2": "Regent Street",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16437859597/",
        "Copyright": "Copyright under review",
        "Subject": "Regent Street",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "59",
        "ImageName": "Weston-super-Mare",
        "Summary": "Regent Street",
        "Description1": "Regent Street",
        "Type": "Postcard",
        "Address2": "Regent Street",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16457583668/",
        "Copyright": "Copyright under review",
        "Subject": "Regent Street",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "60",
        "ImageName": "Weston-super-Mare",
        "Summary": "Rozel Bandstand",
        "Description1": "Regent Street",
        "Type": "Postcard",
        "Address2": "Regent Street",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16619233206/",
        "Copyright": "Copyright under review",
        "Subject": "Regent Street",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "61",
        "ImageName": "Weston-super-Mare",
        "Summary": "Rozel Bandstand",
        "Description1": "Rozel Bandstand",
        "Type": "Postcard",
        "Address1": "Rozel Bandstand",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16457643918/",
        "Copyright": "Copyright under review",
        "Subject": "Rozel Bandstand",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "62",
        "ImageName": "Weston-super-Mare",
        "Summary": "Rozel Bandstand",
        "Description1": "Rozel Bandstand",
        "Type": "Postcard",
        "Address1": "Rozel Bandstand",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16643803541/",
        "Copyright": "Copyright under review",
        "Subject": "Rozel Bandstand",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "63",
        "ImageName": "Weston-super-Mare",
        "Summary": "Rozel Bandstand",
        "Description1": "Rozel Bandstand",
        "Type": "Postcard",
        "Address1": "Rozel Bandstand",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16643803581/",
        "Copyright": "Copyright under review",
        "Subject": "Rozel Bandstand",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "64",
        "ImageName": "Weston-super-Mare",
        "Summary": "Rozel Bandstand",
        "Description1": "Rozel Bandstand",
        "Type": "Postcard",
        "Address1": "Rozel Bandstand",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16459040289/",
        "Copyright": "Copyright under review",
        "Subject": "Rozel Bandstand",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "65",
        "ImageName": "Weston-super-Mare",
        "Summary": "Rozel Bandstand",
        "Description1": "Rozel Bandstand",
        "Type": "Postcard",
        "Address1": "Rozel Bandstand",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16643803611/",
        "Copyright": "Copyright under review",
        "Subject": "Rozel Bandstand",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "66",
        "ImageName": "Weston-super-Mare",
        "Summary": "Rozel Bandstand",
        "Description1": "Rozel Bandstand",
        "Type": "Postcard",
        "Address1": "Rozel Bandstand",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16025320463/",
        "Copyright": "Copyright under review",
        "Subject": "Rozel Bandstand",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "67",
        "ImageName": "Weston-super-Mare",
        "Summary": "Civic Occasion",
        "Description1": "Rozel Bandstand",
        "Type": "Postcard",
        "Address1": "Rozel Bandstand",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145273082",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16023061814/",
        "Copyright": "Copyright under review",
        "Subject": "Rozel Bandstand",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "68",
        "ImageName": "Weston-super-Mare",
        "Summary": "Motorcross",
        "Description1": "Civic Occasion",
        "Type": "Postcard",
        "Address1": "Beach",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17120921496",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16457801018/",
        "Copyright": "Copyright under review",
        "Subject": "Civic Occasion",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "69",
        "ImageName": "Weston-super-Mare",
        "Summary": "Beach",
        "Description1": "Motorcross",
        "Type": "Postcard",
        "Address1": "Beach",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17146869425/",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16459208999/",
        "Copyright": "Copyright under review",
        "Subject": "Motorcross",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      },
      {
        "PublisherLabel": "North Somerset Council",
        "PublisherURI": "http://opendatacommunities.org/dashboard/local_authorities/unitary-authority/north-somerset",
        "ImageRef": "70",
        "ImageName": "Weston-super-Mare",
        "Summary": "Beach",
        "Description1": "Beach",
        "Type": "Postcard",
        "Address1": "Beach",
        "Address2": "Beach Road",
        "Address3": "Weston-super-Mare",
        "Website1": "https://www.flickr.com/photos/discover_north_somerset/17145272372",
        "Website2": "https://www.flickr.com/photos/discover_north_somerset/16458007290/",
        "Copyright": "Copyright under review",
        "Subject": "Beach",
        "Colouration": "Black and white",
        "Source": "North Somerset Council Library Service",
        "SubjectLatitude": "0",
        "SubjectLongitude": "0",
        "OriginLatitude": "0",
        "OriginLongitude": "0"
      }
    ];

    this.getData = function () {
      return $q(function (resolve) {
        resolve(data)
      });
    }


  })
  .service('nsUserDataService', function (nsImagesService, $localstorage) {
    var that = this;
    var foundKey = 'foundPoints';
    this.getFoundPoints = function () {
      return $localstorage.get(foundKey, {});
    };

    this.setPointFound = function (foundPoint) {
      var found = that.getFoundPoints();
      found[foundPoint[nsImagesService.CONSTANTS.REF]] = foundPoint;
      $localstorage.set(foundKey, found);
    };

    this.isPointFound = function (point) {
      return that.getFoundPoints().hasOwnProperty(point[nsImagesService.CONSTANTS.REF]);
    };

  })
  .service('$localstorage', function ($window) {
    return {
      set: function (key, value) {
        $window.localStorage[key] = value;
      },
      get: function (key, defaultValue) {
        return $window.localStorage[key] || defaultValue;
      },
      setObject: function (key, value) {
        $window.localStorage[key] = JSON.stringify(value);
      },
      getObject: function (key) {
        return JSON.parse($window.localStorage[key] || '{}');
      }
    }
  });



